spring:
  application:
    name: spring-cloud-sleuth-zipkin
  main:
    allowBeanDefinitionOverriding: true

server:
  port: 8086

management:
  metrics:
    web:
      server:
        auto-time-requests: false

# Eureka Client配置
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
