spring:
  application:
    name: spring-cloud-web
  zipkin:
    base-url: http://localhost:8086
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8081

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
  threadpool:
    default:
      coreSize: 1
      maxQueueSize: 0

management:
  endpoints:
    web:
      exposure:
        include: '*'
