spring:
  application:
    name: spring-cloud-service
  zipkin:
    base-url: http://localhost:8086
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8082

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
