spring:
  application:
    name: spring-cloud-service
  # Zipkin配置
  zipkin:
    base-url: http://localhost:8086
  # Nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 8082

# Eureka Client配置
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
