spring:
  application:
    name: spring-cloud-zuul
  # Zipkin配置
  zipkin:
    base-url: http://localhost:8086

server:
  port: 8080

# Eureka Client配置
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

# Zuul配置
zuul:
  routes:
    user-service:
      serviceId: spring-cloud-service
      path: /user-service/**
    user-web:
      serviceId: spring-cloud-web
      path: /user-web/**

# Feign配置
feign:
  hystrix:
    enabled: true

# Hystrix配置
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD

management:
  endpoints:
    web:
      exposure:
        include: '*'
